INSERT INTO ds.md_account_d
    SELECT DISTINCT ON (DATA_ACTUAL_DATE, ACCOUNT_RK)*
    FROM temp.md_account_d        
ON CONFLICT (DATA_ACTUAL_DATE, ACCOUNT_RK)
DO UPDATE 
	SET 
		DATA_ACTUAL_END_DATE = excluded.DATA_ACTUAL_END_DATE,
		ACCOUNT_NUMBER = excluded.ACCOUNT_NUMBER,
		CHAR_TYPE = excluded.CHAR_TYPE,
		CURRENCY_RK = excluded.CURRENCY_RK,
		CURRENCY_CODE = excluded.CURRENCY_CODE;