INSERT INTO dm.dm_f101_round_f_v2
    SELECT DISTINCT *
    FROM temp.dm_f101_round_f       
ON CONFLICT (
    FROM_DATE,
    TO_DATE,
    CHAPTER,
    LEDGER_ACCOUNT,
    CHARACTERISTIC,
    BALANCE_IN_RUB,
    R_BALANCE_IN_RUB,
    BALANCE_IN_VAL,
    R_BALANCE_IN_VAL,
    BALANCE_IN_TOTAL,
    R_BALANCE_IN_TOTAL,
    TURN_DEB_RUB,
    R_TURN_DEB_RUB,
    TURN_DEB_VAL,
    R_TURN_DEB_VAL,
    TURN_DEB_TOTAL,
    R_TURN_DEB_TOTAL,
    TURN_CRE_RUB,
    R_TURN_CRE_RUB,
    TURN_CRE_VAL,
    R_TURN_CRE_VAL,
    TURN_CRE_TOTAL,
    R_TURN_CRE_TOTAL,
    BALANCE_OUT_RUB,
    R_BALANCE_OUT_RUB,
    BALANCE_OUT_VAL,
    R_BALANCE_OUT_VAL,
    BALANCE_OUT_TOTAL,
    R_BALANCE_OUT_TOTAL
) 
DO UPDATE 
	SET
        FROM_DATE  = excluded.FROM_DATE,
        TO_DATE  = excluded.TO_DATE,
        CHAPTER	 = excluded.CHAPTER,
        LEDGER_ACCOUNT  = excluded.LEDGER_ACCOUNT,
        CHARACTERISTIC  = excluded.CHARACTERISTIC,
        BALANCE_IN_RUB  = excluded.BALANCE_IN_RUB,
        R_BALANCE_IN_RUB  = excluded.R_BALANCE_IN_RUB,
        BALANCE_IN_VAL  = excluded.BALANCE_IN_VAL,
        R_BALANCE_IN_VAL  = excluded.R_BALANCE_IN_VAL,
        BALANCE_IN_TOTAL  = excluded.BALANCE_IN_TOTAL,
        R_BALANCE_IN_TOTAL  = excluded.R_BALANCE_IN_TOTAL,
        TURN_DEB_RUB  = excluded.TURN_DEB_RUB,
        R_TURN_DEB_RUB  = excluded.R_TURN_DEB_RUB,
        TURN_DEB_VAL  = excluded.TURN_DEB_VAL,
        R_TURN_DEB_VAL  = excluded.R_TURN_DEB_VAL,
        TURN_DEB_TOTAL  = excluded.TURN_DEB_TOTAL,
        R_TURN_DEB_TOTAL  = excluded.R_TURN_DEB_TOTAL,
        TURN_CRE_RUB  = excluded.TURN_CRE_RUB,
        R_TURN_CRE_RUB  = excluded.R_TURN_CRE_RUB,
        TURN_CRE_VAL  = excluded.TURN_CRE_VAL,
        R_TURN_CRE_VAL  = excluded.R_TURN_CRE_VAL,
        TURN_CRE_TOTAL  = excluded.TURN_CRE_TOTAL,
        R_TURN_CRE_TOTAL  = excluded.R_TURN_CRE_TOTAL,
        BALANCE_OUT_RUB  = excluded.BALANCE_OUT_RUB,
        R_BALANCE_OUT_RUB  = excluded.R_BALANCE_OUT_RUB,
        BALANCE_OUT_VAL  = excluded.BALANCE_OUT_VAL,
        R_BALANCE_OUT_VAL  = excluded.R_BALANCE_OUT_VAL,
        BALANCE_OUT_TOTAL  = excluded.BALANCE_OUT_TOTAL,
        R_BALANCE_OUT_TOTAL  = excluded.R_BALANCE_OUT_TOTAL;