CREATE SCHEMA IF NOT EXISTS ds;
-- DROP SCHEMA IF EXISTS ds CASCADE;


-- ft_balance_f – остатки средств на счетах;
CREATE TABLE IF NOT EXISTS ds.ft_balance_f (
    ON_DATE  DATE,
    ACCOUNT_RK INT,
    CURRENCY_RK INT,
    BALANCE_OUT DECIMAL,
    PRIMARY KEY (ON_DATE, ACCOUNT_RK)
);


-- ft_posting_f – проводки (движениясредств) по счетам;
CREATE TABLE IF NOT EXISTS ds.ft_posting_f (
    OPER_DATE  DATE,
    CREDIT_ACCOUNT_RK INT,
    DEBET_ACCOUNT_RK INT,
    CREDIT_AMOUNT DECIMAL,
    DEBET_AMOUNT DECIMAL,
    PRIMARY KEY (OPER_DATE, CREDIT_ACCOUNT_RK, DEBET_ACCOUNT_RK)
);


-- md_account_d – информация о счетах клиентов
CREATE TABLE IF NOT EXISTS ds.md_account_d (
    DATA_ACTUAL_DATE  DATE,
    DATA_ACTUAL_END_DATE DATE,
    ACCOUNT_RK INT,
    ACCOUNT_NUMBER INT,
    CHAR_TYPE VARCHAR(30),
    CURRENCY_RK INT,
    CURRENCY_CODE INT,
    PRIMARY KEY (DATA_ACTUAL_DATE, ACCOUNT_RK)
);


-- md_currency_d – справочниквалют;
CREATE TABLE IF NOT EXISTS ds.md_currency_d (
    CURRENCY_RK  INT,
    DATA_ACTUAL_DATE DATE,
    DATA_ACTUAL_END_DATE DATE,
    CURRENCY_CODE INT,
    CODE_ISO_CHAR VARCHAR(30),
    PRIMARY KEY (CURRENCY_RK, DATA_ACTUAL_DATE)
);


-- md_exchange_rate_d – курсывалют.
CREATE TABLE IF NOT EXISTS ds.md_exchange_rate_d (
    DATA_ACTUAL_DATE  INT,
    DATA_ACTUAL_END_DATE DATE,
    CURRENCY_RK DATE,
    REDUCED_COURCE DECIMAL,
    CODE_ISO_NUM INT,
    PRIMARY KEY (DATA_ACTUAL_DATE, CURRENCY_RK)
);


-- md_ledger_account_s - справочник балансовых счётов
CREATE TABLE IF NOT EXISTS ds.md_ledger_account_s (
    CHAPTER  VARCHAR(30),
    CHAPTER_NAME VARCHAR(30),
    SECTION_NUMBER INT,
    SECTION_NAME VARCHAR(30),
    SUBSECTION_NAME VARCHAR(30),
    LEDGER1_ACCOUNT INT,
    LEDGER1_ACCOUNT_NAME TEXT,
    LEDGER_ACCOUNT INT,
    LEDGER_ACCOUNT_NAME TEXT,
    CHARACTERISTIC VARCHAR(30),
    IS_RESIDENT boolean,
    IS_RESERVE boolean,
    IS_RESERVED boolean,
    IS_LOAN boolean,
    IS_RESERVED_ASSETS boolean,
    IS_OVERDUE boolean,
    IS_INTEREST boolean,
    PAIR_ACCOUNT INT,
    START_DATE DATE,
    END_DATE DATE,
    IS_RUB_ONLY boolean,
    MIN_TERM VARCHAR(30),
    MIN_TERM_MEASURE VARCHAR(30),
    MAX_TERM VARCHAR(30),
    MAX_TERM_MEASURE VARCHAR(30),
    LEDGER_ACC_FULL_NAME_TRANSLIT VARCHAR(30),
    IS_REVALUATION boolean,
    IS_CORRECT boolean,
    PRIMARY KEY (LEDGER_ACCOUNT, START_DATE)
);